### ISSUE TITLE
better solution in R for passing range by parameters

### ISSUE THREAD

**Issue by ksens** [Paradigm4/revealgenomics-apps#14]
@mmccorry 

Take a look at the function `formulate_filter_by_value_range_query` at https://github.com/Paradigm4/revealgenomics-demo/blob/master/revealsc/R/sc_helper_functions.R#L1 (the test cases just below the function definition provide example usage for the function).

From the biobank package or elsewhere, do you have a better solution in R for passing range by parameters. 

Also we need to figure out how to handle `gte`, `lte`.

**Comment by mmccorry** [comment]
This has been implemented for `revealsc_search_expression()` with commit 0d96186019a4caaa500789d6507cefdfec8cc289

Keeping this open until this has been added to `revealsc_search_cells()` as well.

**Comment by ksens** [comment]
The remaining functionality was added to `revealsc_search_cells` by @mmccorry . Closing issue.
