### ISSUE TITLE
Output expected by REST API tests for `GET /project` needs to change

### ISSUE THREAD

**Issue by ksens** [Paradigm4/revealgenomics-apps#24]
Python tests expected

```sh
{
  {
  },
  ...
}
```

Instead it is likely that this should be returned (@arko-bhattacharya to investigate)
```sh
[ 
  {
  },
  ...
]
```

**Comment by mmccorry** [comment]
@arko-bhattacharya @ksens 

This may have to do how the plumber package is implicitly converting the `data.frame`/`data.table` of projects to a JSON string.

Some things to try:
- try wrapping the output in `list()` or `as.list()`
- do the conversion to JSON explicitly inside the server code for `/project` and direct `plumber` to return the formulated JSON string and not do an additional conversion.

**Comment by ksens** [comment]
Closing issue. Resolved in #29. 

Copying text from that ticket for reference:

- Return list instead of data.frame
- Return Unboxed JSON (R returns boxed JSON by default). Storing some links for reference
    + Section on "Boxed vs Unboxed JSON" at https://www.rplumber.io/docs/rendering-and-output.html
    + https://stackoverflow.com/questions/42592738/how-to-send-json-response-using-plumber-r
