### ISSUE TITLE
Need to add API versioning to REST API

### ISSUE THREAD

**Issue by ksens** [Paradigm4/revealgenomics-apps#38]
Suggested format would be something like:

```
<IP>:9000/api/v0/
```

R `plumber` does not seem to have a variable to handle this. Workaround -- define endpoints as:

```
#* @get /api/v0/project
```

instead of
```
#* @get /project
``` 

Unassigned for now. @mmccorry or I will pick this up depending on availability.

**Comment by ksens** [comment]
@mmccorry Could you try and take this on before our Monday TCon? If not, you can mention at the meeting that we have a solution and will deploy soon.

**Comment by mmccorry** [comment]
@ksens I will take a try to get this done before then.  I'll do another check of plumber documentation to see if there's a more elegant way to handle this.
