### ISSUE TITLE
Add REST endpoint to POST cells and expression data for existing sample

### ISSUE THREAD

**Issue by mmccorry** [Paradigm4/revealgenomics-apps#41]
Once a sample has been created, we also need to enable POSTs of cells and expression data for the sample post hoc using the following endpoint:

```
POST /project/{projectid}/sample/{sampleid}
```

**Comment by ksens** [comment]
You might already have noticed, but pointing out just in case -- 

`1.` The following endpoint will get deprecated in favor of the one described here:

```
@post /project/<projectid>/sample/<sampleid>/expression
```

In fact, you should be able to reuse a lot of the code from the `POST .../expression` endpoint for the proposed endpoint. 

`2`. Earlier, `POST /project/{projectid}/sample/{sampleid}` used to allow uploading barcodes. That functionality would be subsumed by the functionality proposed in this ticket.

**Comment by mmccorry** [comment]
@ksens I have the expression endpoint now working with a customer's tests.  Will now move into the endpoint `POST /project/{projectid}/sample/{sampleid}`

**Comment by mmccorry** [comment]
Addressed in https://github.com/Paradigm4/revealgenomics-apps/pull/42
