### ISSUE TITLE
Add SciDB reconnect logic to REST server

### ISSUE THREAD

**Issue by mmccorry** [Paradigm4/revealgenomics-apps#57]
Wrap calls to `revealsc` in the REST server code that use a DB connection object with a `trycatch({})` and reconnect on failure:

Adapt from https://github.com/Paradigm4/biobank/issues/160

**Comment by apoliakov** [comment]
Guys one thing to think about here

Doing this in a client (a shiny app) is one thing but doing it in an API is riskier. It essentially forces you to store the password in the API itself.

Think about it

**Comment by mmccorry** [comment]
@apoliakov -
We are aware of this concern.  For now, we are intending for this will be stored in the REST API server instance only -- not in the `revealgenomics` API or `revealsc` API.

Longer term, we need a more secure solution.  From within the R connectors/APIs (e.g., `revealsc`), we can simply throw a message saying that the user needs to reconnect to the database.

Trickier for a persistent REST server, as is the current problem.

**Comment by apoliakov** [comment]
Roger! Sorry! Just being a jetlagged idiot. I now remember we discussed
this already.

**Comment by ksens** [comment]
@mmccorry seems this is OK to close now?

**Comment by mmccorry** [comment]
@ksens Yep, closing this ticket as this has been resolved in https://github.com/Paradigm4/revealgenomics-apps/pull/59 and https://github.com/Paradigm4/revealgenomics-apps/pull/75
