### ISSUE TITLE
Malformed tags for `GET /project` when server deployed as service

### ISSUE THREAD

**Issue by ksens** [Paradigm4/revealgenomics-apps#60]
When deployed as a service, `http://<IP>:9000/api/v0/project`

yields

```
{
"projects": [
{
"projectid": "10x Genomics",
"href": "/project/10x%20Genomics",
"tags": {
"desc": false,
"newTag1": true,
"newTag2": true,
"owner": false,
"project_description": true,
"RACode": false,
"someTag": false,
"sometagkey": false,
"url": true
}
},
```

but when run from R console as:
```
setwd('~/coding/revealgenomics-apps/rest-api/r-server/');
plumber::plumb("~/coding/revealgenomics-apps/rest-api/r-server/scrnaseq-server.R")$run(port = 9002, host = "0.0.0.0")
```

`http://<IP>:9002/api/v0/project` yields:

```
{
"projects": [
{
"projectid": "10x Genomics",
"href": "/project/10x%20Genomics",
"tags": {
"newTag1": "newValue3",
"newTag2": "3345",
"project_description": "Single Cell Gene Expression Datasets",
"url": "https://support.10xgenomics.com/single-cell-gene-expression/datasets/"
}
},
...
```

**Comment by mmccorry** [comment]
@ksens 

Might this be due to installed package versions?  We are running plumber in R using user `root`, correct?

**Comment by ksens** [comment]
Let me check that.

Will remove all packages from user's home directory -- that way, the local run of plumber is bound to use the packages available to all users and `root`.

**Comment by ksens** [comment]
@mmccorry 

Yup, it was an issue with package versions. 

Turns out the latest version of `revealgenomics` is causing the issue due to [this bug](https://github.com/Paradigm4/revealgenomics/issues/103). Can you take a look?

**Comment by ksens** [comment]
Fixed with 

- patch https://github.com/Paradigm4/revealgenomics/pull/104
- reinstalling `revealgenomics` API on scrnaseq server
- restarting REST API

Need to tell client side users to reinstall `revealgenomics`. Closing issue.
