### ISSUE TITLE
Stop trying to reconnect after 5-6 seconds of trying

### ISSUE THREAD

**Issue by ksens** [Paradigm4/revealgenomics-apps#74]
@mmccorry 

Was thinking about this a bit more.

Say we have the following scenario:

- scidb server / shim server is actually down
- client tries a REST API call
- REST API server code hits the reconnect logic, and tries to reconnect every 5 seconds
- this keeps going on, client does not get any response
- after a while, client kills their request
- reconnection attempts keep happening every 5 seconds, and REST API is unresponsive to future calls

If this is the case, I would suggest that the reconnect logic tries to reconnect every 1 second around 5 times and then give up and provide a meaningful message to client.

Maybe you already have some logic to circumvent this. Let's discuss.

**Comment by mmccorry** [comment]
@ksens 

About to submit a PR that addresses this.

A timeout in the reconnect logic will result in the connection object being `NULL`.  I updated the error handling in the `tryCatch()` to handle the case where we could not perform a subsequent queries after a timeout.
